### ISSUE TITLE
Running-cue Related Time Variables don't Work in QL5

### ISSUE THREAD

**Issue by oneiropagides** [bitfocus/companion-module-figure53-qlab-advance#101]
Hi team, 

All variables regarding the running cue times bring not data back or don't update:
$(qlabfb:e_time) --> This displays the duration of the cue, and not the time elapsed, so it's a static number. 
$(qlabfb:r_left) --> This is always 00 and does not display the time left. 

The same is true for all other running cue related variables. 

Is that something that can be fixed?

**Comment by istnv** [comment]
Which version of companion? 
These both work on Companion v3.0.1 and v3.1.0.

**Comment by oneiropagides** [comment]
> Which version of companion? These both work on Companion v3.0.1 and v3.1.0.

I am running 3.01 on my Mac, and as things are as I wrote above. 
Am I doing something wrong?
Because everything else is working fine.

**Comment by istnv** [comment]
Would you mind sharing your show file? Since QLab can run dozens of cues at once, the module sometimes has trouble finding the 'best one' to use for running/elapsed time.

**Comment by oneiropagides** [comment]
> Would you mind sharing your show file? Since QLab can run dozens of cues at once, the module sometimes has trouble finding the 'best one' to use for running/elapsed time.

Hi John, since you mentioned v3.10, I just updated my companion to that version, and it now works fine!
It was in 3.01 that did not work, but after upgrading, I don't have any problems any more.

**Comment by istnv** [comment]
There were a lot of QLab5 specific fixes added yesterday.

**Comment by oneiropagides** [comment]
> There were a lot of QLab5 specific fixes added yesterday.

Fantastic! Thank you so much for your quick reply!
