### ISSUE TITLE
Problems with ID

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion-module-figure53-qlab-advance#107]
I get an error message about the unique QLab ID, also the buttons show a red square but they work. See attached screen shots.
<img width="1115" alt="Bildschirmfoto 2023-11-13 um 11 55 03" src="https://github.com/bitfocus/companion-module-figure53-qlab-advance/assets/6450325/bc84bc33-e1c7-4e0b-901c-b9843914eaed">
<img width="1115" alt="Bildschirmfoto 2023-11-13 um 11 55 26" src="https://github.com/bitfocus/companion-module-figure53-qlab-advance/assets/6450325/4ce1c088-58b2-44c8-bf60-daa11a19d773">

**Comment by istnv** [comment]
Which version of QLab?

**Comment by sstaub** [comment]
5.3 and 5.3.1Am 14.11.2023 um 21:09 schrieb John Knight Jr ***@***.***>:﻿
Which version of QLab?

**Comment by istnv** [comment]
I have not upgraded that far. I'll take look soon.

**Comment by istnv** [comment]
QLab has changed something in their response to queries. The buttons will work but some of the feedback and variables will not.
