### ISSUE TITLE
BUG $(INSTANCENAME:q_{num}_name) and $(INSTANCENAME:id_{ID}_name) doesn't work anymore

### ISSUE THREAD

**Issue by Edsonius** [bitfocus/companion-module-figure53-qlab-advance#110]
After the upgrade from module version 2.2.2 to 2.5 the Variabele $(INSTANCENAME:q_{num}_name) and $(INSTANCENAME:id_{ID}_name)  give always $NA.
I havy tried it with q_5_name so there are no strange characters in the cue name.
I use the companion ARM version for mac.
The stable Companion version 3.1.2 with Qlab module with feedback 2.2.2 is okay
The stable Companion version 3.2.0 with Qlab module with feedback 2.5.0 is broken.

**Comment by istnv** [comment]
Which version of QLab?

**Comment by istnv** [comment]
An option was added to expose these variables in the drop-down list that missed setting them up if the option was off.
You can enable the `Expose cue name variables?` option until the update publishes.
![image](https://github.com/bitfocus/companion-module-figure53-qlab-advance/assets/51003420/c196bfed-7497-4e8b-87d4-e4c56231fe32)
