### ISSUE TITLE
Show / Edit mode no longer functions on newest update of Companion

### ISSUE THREAD

**Issue by DrumFunKen** [bitfocus/companion-module-figure53-qlab-advance#112]
Show / Edit mode no longer functions on newest update of Companion

**Comment by istnv** [comment]
Which version of QLab ?

**Comment by DrumFunKen** [comment]
> Which version of QLab ?

5.3.3 on mac os Sonoma 14.3

**Comment by istnv** [comment]
Found a typo. Should have a fix later today. Apparently I had help last week.
![image](https://github.com/bitfocus/companion-module-figure53-qlab-advance/assets/51003420/d72e1483-834c-4648-b768-283b96c4fac8)

**Comment by DrumFunKen** [comment]
Thanks for Your Efforts!!!

**Comment by istnv** [comment]
PR #113

**Comment by kineticscreen** [comment]
BTW this has fixed setting Show mode and Arm Cue on and off, but there is an issue with the 'toggle' option.
For arming cues, it can toggle the armed state 'off', but then won't toggle to 'on'.
For show mode, the arm state will toggle to edit mode, but won't toggle back to show.

I'll update if/when I find more.

**Comment by istnv** [comment]
Should be fixed today, PR #114

**Comment by kineticscreen** [comment]
Awesome. While I've got your attention, is it possible to get feedback for armed state of a cue?
