### ISSUE TITLE
Arm / Disarm specific cue and feedback

### ISSUE THREAD

**Issue by kineticscreen** [bitfocus/companion-module-figure53-qlab-advance#115]
Just wondering if this is technically possible to include? Instead of the current arm / disarm, which affects the current selected cue, instead to be able to actually target a cue by qname or ID to arm / disarm it?
And along with that, to have feedback on the status of a specific cue, as to whether it is armed or disarmed?

**Comment by istnv** [comment]
I have been working on adding this to several commands for a while. I do not have any spare time at the moment to do much more.
