### ISSUE TITLE
Error when conecting with QLab5

### ISSUE THREAD

**Issue by 0xJasine** [bitfocus/companion-module-figure53-qlab-advance#123]
**Software Versions:**
QLab 5.3.8
Companion v3.2.2+6688-stable-7417d2a0
Figure 53: QLab with feedback v2.5.3

**Configuration**

_QLab Companion AddOn_
Target Host/IP > 127.0.0.1
Target Port > 53000
Use TCP? > No/Yes (Tried both)
Use Tenths? > No
Expose cue name variables? > No
OSC Passcode > None
Workspace > Training
Specific Cue List > Default Cue List

_QLab Configuration_
Network
![Bildschirmfoto 2024-05-12 um 19 41 11](https://github.com/bitfocus/companion-module-figure53-qlab-advance/assets/66537908/a6a804e6-8bb0-459a-b813-6f84f192709c)
Tried UDP and TCP

_OSC Acces_
![Bildschirmfoto 2024-05-12 um 19 43 56](https://github.com/bitfocus/companion-module-figure53-qlab-advance/assets/66537908/32fd2c8a-ac60-42c5-a41b-1ee9d865b2f9)

**The Problem**

https://github.com/bitfocus/companion-module-figure53-qlab-advance/assets/66537908/da97f4e5-a6b3-42df-9346-0bc195cdbd51

**Other usefull files:**
[MacBook-Pro-von-Jason.local_companion_log_20240512-1953.csv](https://github.com/bitfocus/companion-module-figure53-qlab-advance/files/15287179/MacBook-Pro-von-Jason.local_companion_log_20240512-1953.csv)

**Comment by istnv** [comment]
@0xJasine I am unable to reproduce this using that version or the latest (beta).
Are you able to send me a copy of your show file?

**Comment by 0xJasine** [comment]
Yea sure, assuming you mean the QLab show file.

[Show.zip](https://github.com/bitfocus/companion-module-figure53-qlab-advance/files/15287968/Show.zip)

**Comment by istnv** [comment]
@0xJasine 
I could not get the module to fail. I do not use the plugin so I do not know what could happen there.
There are error messages that are comments about the state of the workspace. The module asks for data about the current Playhead. If the playhead is not set, QLab is new returning an 'error', where earlier QLab versions ignored the request.
Even with that notation, the module should still stay connected.
I have updated the module to catch those and filter them out of the log. They will be in betas sometime today.
There is also a new companion plugin released.

**Comment by 0xJasine** [comment]
Yea the update fixed everything tysm.
