### ISSUE TITLE
Elapsed & Remaining time feedback variable stops when playing a looping playlist.

### ISSUE THREAD

**Issue by Matchaow** [bitfocus/companion-module-figure53-qlab-advance#125]
Hi,

Elapsed & remaining cuehead time feedback stops at 0:00 for a looping playlist. Works fine for the first loop but then doesn't reset and count down/up again. I think this is because the feedback comes from the first cue in the list which is the group header that only counts down once. and the cues inside carry on underneath this cue in the active cuestack.

Companion 3.2.2 - Raspberry Pi
Qlab 5.3.8 - macOS Sonoma14.3 / Monterey 12.7.5

Thanks
Matt

**Comment by istnv** [comment]
Have you tried Companion 3.3?
There were several recent updates that were not in 3.2

**Comment by Matchaow** [comment]
Not yet,

 

That popped up as a new version half way through the Job, I’ll report back if there same issue occurs on 3.3

 

Thanks for the replies!

 

Matt
