### ISSUE TITLE
ERROR Can't connect to QLab Cannot read properties of undefined (reading 'includes') In companion connections

### ISSUE THREAD

**Issue by Matchaow** [bitfocus/companion-module-figure53-qlab-advance#126]
Getting a "ERROR Can't connect to QLab Cannot read properties of undefined (reading 'includes')" in the connections tab.

Doesn't appear to affect the running of the module at all but shows up as an error on the companion buttons.

Companion 3.2.2 - Raspberry Pi
Qlab 5.3.8 - macOS Sonoma14.3 / Monterey 12.7.5

Thanks
Matt

**Comment by istnv** [comment]
fixed in current release
