### ISSUE TITLE
Arm Cue Action

### ISSUE THREAD

**Issue by dherlein** [bitfocus/companion-module-figure53-qlab-advance#130]
Using the Arm Cue Action causes the module to throw this error: "ERROR
Can't connect to QLab cue_id is not defined" however, buttons continue to function despite the module claiming it cannot connect and all of the buttons having a red square in the upper right corner.

It doesn't seem to matter whether its set to Arm, Disarm, or Toggle

**Comment by istnv** [comment]
Which companion and QLab versions?

**Comment by dherlein** [comment]
companion 3.3.1
QLab 5.3.6

**Comment by istnv** [comment]
Beta release tonight should fix this
