### ISSUE TITLE
Update current playhead

### ISSUE THREAD

**Issue by Torinth** [bitfocus/companion-module-figure53-qlab-advance#133]
I am looking for a way to use the current playhead name variable but i want each time i use next and back to change the playhead for the variable to be updated so i can have text on the button that shows current playhead.  Is this possible?

**Comment by istnv** [comment]
That is exactly how the `$(qlabfb:n_name)` variable works. All of the variables on the `$` variable list update automatically depending on the state of the workspace.

**Comment by Torinth** [comment]
I tried that but it’s not updating.  If I go to connections and disable then re enable it updates but won’t do it live. I did also notice that if I enable the connection I get a green check mark but then I go away from the screen and come back there is an error saying can’t read from undefined object. However while this error is there commands and feedbacks still work. Maybe this has something to do with variables not updating?  I’m using the latest stable 3.3.1 of companion.
________________________________

**Comment by istnv** [comment]
Which version of QLab? Is companion running on the same Mac?

**Comment by Torinth** [comment]
The latest version 5.4.3. It's not running on the same Mac but communication does seem to happen in both directions since variables do initially get populated. I can also pick the specific cuelist in the connection but I have first save it , disable re enable then I have the workspace list select one, disable re enable wait a few seconds then I can pick the specific cuelist to connect to. Something weird on subsequent updates
________________________________

**Comment by istnv** [comment]
Click on the `>_` on the connection row. That will open a more detailed debug log. 
I have just tried linux, windows 11, and Macos Companion 3.1.1 controlling QLab 5.4.3 without any errors or odd behaviour.

**Comment by Torinth** [comment]
i got an error message

info: Address "/workspace/E9A56FCC-92E0-4A52-AA14-0A0FF3D60FCF/cue/B37CF1AA-047A-4D62-87AD-D7FFCD4A4F2F/playheadID" returned an error
________________________________

**Comment by Torinth** [comment]
Look like a new update to 5.4.4 still get that same error
________________________________

**Comment by Torinth** [comment]
I changed the workspace from edit mode to show mode and this error popped up

info: Address "/workspace/E9A56FCC-92E0-4A52-AA14-0A0FF3D60FCF/auditionWindow" returned an error
________________________________

**Comment by Torinth** [comment]
When i look at the osc dictionary on qlabs website it looks like there are some incorrect requests from the companion plugin.

for playheadid they show

/workspace/{id}/playheadID/{cue_id}
but the companion module is sending
/workspace/{id}/cue/{cue_id}/playheadID

________________________________

**Comment by Torinth** [comment]
or nevermind, in the cue section it shows always sending workspace before it
________________________________

**Comment by Torinth** [comment]
Ok i think maybe this is it.

For all cue OSC messages, any instance of the address pattern /cue/{cue_number} can be replaced by the equivalent unique ID address pattern /cue_id/{id}.

the module is sending
info: Address "/workspace/E9A56FCC-92E0-4A52-AA14-0A0FF3D60FCF/cue/897682B5-918E-41C5-A870-410786E779AF/playheadID" returned an error

so i think it should be sending

/workspace/E9A56FCC-92E0-4A52-AA14-0A0FF3D60FCF/cue_id/897682B5-918E-41C5-A870-410786E779AF/playheadID

________________________________

**Comment by istnv** [comment]
When you specify a single cuelist it will prefix all necessary commands. That is normal. 
Somehow the module is losing the qlab 5 vs 4 .
The errors are from the module sending version 4 commands that changed in version 5. 
I'm away from the computer so I won't be able to investigate further for a few hours.

**Comment by Torinth** [comment]
Gotcha no problem at all. Thanks a bunch for helping. It’s been driving me nuts lol
________________________________

**Comment by Torinth** [comment]
Found it.  its checking qlab v4 or  to have the Id versus ID but its not checking it when creating the command

Line 492 is the culprit.

rePulse() {
            const now = Date.now()
            const phID = this.qVer < 5 ? 'Id' : 'ID'

            if (0 == this.pollCount % (this.config.useTenths ? 10 : 4)) {
                  this.sendOSC('/overrideWindow', [], true)

                  this.sendOSC((this.cl ? '/cue/' + this.cl : '') + `/playhead${phID}`, [])
________________________________

**Comment by istnv** [comment]
The command is correct. Once `phID` is set, it gets used in the template as `${phID}`.
Somehow `this.qVer` is not set properly before that point. 
I just got back and will look at this shortly.

**Comment by Torinth** [comment]
Ok cool. I changed locally /cue/ to /cue_id/ and it fixes that issue for me for the moment. It doesn't seem to fix the other issue after sending a command getting the .includes error. There are a couple of spots that do something like this.cueList[cl].includes( that tomorrow I was gonna locally add some logging to see if any of those are causing the error.
________________________________

**Comment by istnv** [comment]
PR #134 
That has actually been broken for a while. The `includes` error was a string split then an incorrect '0' or '1' based index.
Both `/cue/` and `/cue_id/` work in QLab4. Only `/cue_id/` works in QLab5.
Works for both, now. It will be in the betas soon.
