### ISSUE TITLE
Arm/disarm Cue error

### ISSUE THREAD

**Issue by makesbadnoise** [bitfocus/companion-module-figure53-qlab-advance#137]
Whenever I use the Arm/disarm toggle, the action works but Companion throws an error saying "Can't connect to QLab cue_id is not defined" It doesn't matter if there's a cue number with the cue or not, or what type of cue it is.

**Comment by istnv** [comment]
Which version of Companion?

**Comment by makesbadnoise** [comment]
3.3.1




Nathan Cooper

Head of Audio

Nomad Event Systems

703-354-2939 <7033542939>

3211 Colvin St, Alexandria, VA 22314, United States
***@***.***,-77.0878641,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b19dc4c454f5:0x442d48d373a34b99!8m2!3d38.8073521!4d-77.0856754>

nomadevents.com

The content of this email is confidential and intended for the recipient
specified in message only. It is strictly forbidden to share any part of
this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and
follow with its deletion, so that we can ensure such a mistake does not
occur in the future.

**Comment by istnv** [comment]
That issue was fixed in the beta release.

**Comment by makesbadnoise** [comment]
Awesome, thanks!




Nathan Cooper

Head of Audio

Nomad Event Systems

703-354-2939 <7033542939>

3211 Colvin St, Alexandria, VA 22314, United States
***@***.***,-77.0878641,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b19dc4c454f5:0x442d48d373a34b99!8m2!3d38.8073521!4d-77.0856754>

nomadevents.com

The content of this email is confidential and intended for the recipient
specified in message only. It is strictly forbidden to share any part of
this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and
follow with its deletion, so that we can ensure such a mistake does not
occur in the future.
