### ISSUE TITLE
Request - Current Selected Loaded Time

### ISSUE THREAD

**Issue by Torinth** [bitfocus/companion-module-figure53-qlab-advance#142]
Hello i was wondering if its possible to have a variable that is currently selected loaded time.  I am using the load at action against selected with increase and decrease and that works great but would also like a variable showing the currently loaded time of selected if possible.

Thank you

**Comment by istnv** [comment]
That will be in an update coming out soon.

**Comment by istnv** [comment]
Look at the 'Elapsed' variables
