### ISSUE TITLE
Request - Select command

### ISSUE THREAD

**Issue by Torinth** [bitfocus/companion-module-figure53-qlab-advance#145]
Hello, i would like to see if the select command can be implemented.

/workspace/{id}/select/{cue_number}
/workspace/{id}/select_id/{id}

Thank you

**Comment by istnv** [comment]
The 'Go To Cue' command does that.

**Comment by Torinth** [comment]
The goto cue moves the playhead to the cue but the cue is not selected.  so when i use something like the load at time with "selected" option and increase/decrease it does not work.  Also i dont want the playhead and cue i have selected to be the same in the case im using so for now im using the custom osc command to achieve what i need.

**Comment by istnv** [comment]
I also thought I had recently put in a 'select cue' action. 
The documentation is ready but I never finished it.

**Comment by istnv** [comment]
Currently in Alpha, there are also scope options for `Load at`, `Pre-wait`, `Post-wait`, `Duration`, and others. This lets you choose which cue gets modified: `Selected`, `Playhead`, `Cue Number`, or `Cue ID`.
Also variables for these which should cover your other request (#142)
This update pass is almost ready.

**Comment by istnv** [comment]
Had to take time out for the real job that keeps the bills paid :)

**Comment by Torinth** [comment]
Awesome thank you so much!
________________________________

**Comment by istnv** [comment]
Should be in an upcoming beta release.
