### ISSUE TITLE
Specific Cue List (possible bug)

### ISSUE THREAD

**Issue by micpool** [bitfocus/companion-module-figure53-qlab-advance#151]
I may have missed something in the documentation, but I am unclear what actions the Specific Cue List in the configuration filters.

GO clearly applies only to the specific cue list, and I can see that the cue ID of the cue list is part of the OSC address received by QLab:

**OSC received from TCP 192.168.1.57:52941: /workspace/8BA539C0-9041-4E6B-BBF5-775F46B61F5F/cue_id/D2C706D7-6B33-44BD-BA0C-E62E75470DF3/go**

My main confusion is with Panic (ALL) and Panic (ALL) In Time. 
PANIC (ALL) is only applied to the specific cue list specified and QLab's OSC Input Log shows:

**OSC received from TCP 192.168.1.57:52941: /workspace/8BA539C0-9041-4E6B-BBF5-775F46B61F5F/cue_id/D2C706D7-6B33-44BD-BA0C-E62E75470DF3/panic**

PANIC (ALL) IN TIME, however, applies to all cue lists in the workspace, and the OSC received is:

**OSC received from TCP 192.168.1.57:52941: /workspace/8BA539C0-9041-4E6B-BBF5-775F46B61F5F/panicInTime 5**

Is this the intended behaviour?

Thanks

**Comment by istnv** [comment]
They should both be cue-list specific. There were a couple of code refactors around the time Companion 3.0 came out. 
An internal list of Cue List specific commands missed including the `panicIntime` variation. 

_Panic (ALL)_ was an unfortunate choice of names as I would have preferred that to be a Global/Workspace panic.
There should be another action which does a global panic.

**Comment by istnv** [comment]
This should be fixed soon. I had a hip replaced last week and the meds are finally wearing off enough to let the brain function again :)
