### ISSUE TITLE
Playhead Variables

### ISSUE THREAD

**Issue by micpool** [bitfocus/companion-module-figure53-qlab-advance#152]
Playhead Variables data persists from last playhead position when there is no playhead position in the cue list.https://github.com/user-attachments/assets/9921f923-bc77-4470-9bb1-e2edcc9c0fe0

**Comment by istnv** [comment]
Fix coming soon. This is regression from trying to reduce network traffic.
QLab sends an '/update' message when the playhead changes, and I had expected one when the playhead is unset.
Other than constantly asking for the playhead info, there is no way to tell it is un-set.
