### ISSUE TITLE
0 sent instead of decimal when setting increase/decrease prewait

### ISSUE THREAD

**Issue by jwnremt** [bitfocus/companion-module-figure53-qlab-advance#19]
When you are sending a decimal value, ie 0.5/.5 seconds, for a Prewait time (qlabfb: Increase Prewait or qlabfb: Decrease Prewait) the OSC message that is sent is "/cue/selected/preWait/+ 0"

The decimal value is ignored and a 0 value is sent causing the command to fail.

If i send 1.5 then it sends "/cue/selected/preWait/+ 1"

Decrease Prewait does the same thing.

**Comment by istnv** [comment]
All of the time +/- actions currently send the 'seconds' as an integer, while QLab allows decimal/float arguments. I should be able to look into this over the next couple of days.
