### ISSUE TITLE
[Feature request] Specify cue list for dynamic variables

### ISSUE THREAD

**Issue by philglenny** [bitfocus/companion-module-figure53-qlab-advance#21]
I often operate QLab with multiple cue lists, eg. main cue list for sound effects, another cue list for MD to operate click tracks. It'd be great to have a dynamic variable which shows the 'Playhead Cue Name' just for the second cue list. Thanks!

**Comment by istnv** [comment]
The way the module interacts with QLab, this would need a configuration option to specify which Cue List to control. 
Currently, each instance has a configuration for workspace: blank or 'default' (control the front/active workspace) or enter a specific workspace ID.

**Comment by istnv** [comment]
There is now a config option to restrict variables to a specific cuelist.
