### ISSUE TITLE
QLab export and import doesn't retain the "Instance feedback" that's set

### ISSUE THREAD

**Issue by RoelJHengeveld** [bitfocus/companion-module-figure53-qlab-advance#23]
I made a template for Companion on my iMac to work with the qlabfb instance, but when I wanted to export and import that configuration to my MacBook it didn't retain the Instance feedback that I had set. I tried to import the setup to another MacBook and same result.

**Comment by krocheck** [comment]
Which build number are you running?

**Comment by RoelJHengeveld** [comment]
Companion v2.0.0 (2.0.0-5cee140-2244)

**Comment by WNTLtd** [comment]
I just tried that - same version of Companion 2244 - and it works fine for me.
Using Chrome Version 80.0.3987.132 (Official Build) (64-bit) on Mac OS Mojave v10.14.6.

**Comment by RoelJHengeveld** [comment]
Thanks for your feedback. I have retried the procedure aswel after having done it already twice to two different MacBooks, but now it works fine. I don't know where the issue is coming from but probably a user error then?
My apologies!

**Comment by RoelJHengeveld** [comment]
Now that we're in conversation, I really love the feedback options in this instance of QLab. You think it's also possible to get a readout from the duration of the playhead?

**Comment by istnv** [comment]
@RoelJHengeveld Did you look at the dynamic variables available? 
Click on the (?) next to the module name on the instances page.
