### ISSUE TITLE
[Feature Request]  GO button Red/Green

### ISSUE THREAD

**Issue by taylorglad** [bitfocus/companion-module-figure53-qlab-advance#41]
Love the feedback options available.

One suggestion I have...
On QLab's GUI, when I increase the "minimum time between each GO", the GO button on QLab turns red, and turns green again once another GO can be taken.
Is that something that can easily be implemented as a feedback feature with companion? Cause I would find that pretty useful.

**Comment by istnv** [comment]
It is possible but not simple. My macbook is not currently set up for development so I can't do this at the moment.
I see another timer in the near future :)
