### ISSUE TITLE
Multiple Cuelist Control

### ISSUE THREAD

**Issue by arcmusicman** [bitfocus/companion-module-figure53-qlab-advance#42]
First, thank you for creating a fantastic piece of software.  However, I am encountering issues using multiple instances of the module connecting to QLab on the same system.  Here is my setup:  I have two cuelists I need to have independent control over:  Cuelist A and Cuelist B.  I configure each instance of qlabfb in companion to have a unique name, connect to 127.0.0.1, and enable TCP feedback.  After that, I refresh the page and select 'Specific Cuelist' A for one and 'Specific Cuelist' B for the other.  Then, using the feedback variables, I populate some buttons to show the current playhead cue number and cue description.  It all makes sense, but does not function correctly most of the time.

Instead, the behavior is this: regardless of the qlabfb connection instance referenced by the companion buttons, the QLab cuelist controlled and feeding back data is the one most recently in the foreground.  This may be a QLab limitation or it may be your module.  

I have tried multiple approaches to solve this issue:
-Referencing the public IP address instead of localhost
-Moving the cuelist to another workspace and referencing that workspace instead (even assigning different pin codes to the different workspaces)
-Restarting QLab/the Session/Companion in different order

Frustratingly, the multiple cue lists occasionally work correctly, but it is very rare.  This issue has persisted across multiple setups/systems/operating systems all running the latest public release of Companion.  

Any insight you could offer would be greatly appreciated.

**Comment by arcmusicman** [comment]
First Config
![126201084_2565388670428245_7439444586857926873_n](https://user-images.githubusercontent.com/37028836/99714607-a3e43f80-2a5a-11eb-800b-0de73ef12632.jpg)

Second Config
![126575708_2565388903761555_1084329173521273728_n](https://user-images.githubusercontent.com/37028836/99714620-a8105d00-2a5a-11eb-97e5-f01b0ba144f6.jpg)

On the few occasions it works....
![126270488_2565395107094268_5745244074706172758_n](https://user-images.githubusercontent.com/37028836/99714723-cc6c3980-2a5a-11eb-830d-1ff13d64b75e.jpg)

**Comment by istnv** [comment]
Do you have a showfile you can share? If not, I'll try and put something together. I have some time to set up my macbook and dig into this.
Are you Paddy on Facebook?

**Comment by arcmusicman** [comment]
Thanks for responding!

Yes I am Paddy on Facebook, and I will send you the show file tomorrow when
I get to work. Have a good night!

-Patrick

**Comment by arcmusicman** [comment]
I recreated the issue here again.  Any help would be greatly appreciated!

-Patrick

**Comment by istnv** [comment]
Are your label buttons the playhead/next cue or the running cue?

**Comment by arcmusicman** [comment]
The label buttons are the playhead cue.

**Comment by arcmusicman** [comment]
Have you been able to reproduce the issue?

**Comment by istnv** [comment]
Yes. When the patch gets included into the build it should work correctly.

**Comment by arcmusicman** [comment]
Fantastic, thank you very much!  Is there an interim version I could use
for the shows opening this week?

**Comment by istnv** [comment]
Looks like it is in today's build.

**Comment by arcmusicman** [comment]
Awesome, thanks for the update!

**Comment by istnv** [comment]
Closing this. Re-open if it is still an issue.
