### ISSUE TITLE
[BUG] qlabfb:r_ comands are not working

### ISSUE THREAD

**Issue by Gernot1984** [bitfocus/companion-module-figure53-qlab-advance#48]
Beim Q-Lab mit Feedback funktionieren die "Next" ("qlabfb:n_") Befehle problemlos! 
Die "running" ("qlabfb:r_") Befehle leider alle nicht!

Mit freundlichen Grüßen

**Comment by istnv** [comment]
The 'r_..' variables depend on the module being able to find an appropriate 'Running' cue. 
QLab can run dozens of cues at once, so the module tries to locate one running cue that has a time count.
The way cues are grouped in the workspace can also affect the ability to locate a good cue to follow.

**Comment by istnv** [comment]
Need more info to investigate. Closing for now.
