### ISSUE TITLE
Swedish characters (åäö ÅÄÖ) in cue names not working all the time with $(INSTANCENAME:r_name)

### ISSUE THREAD

**Issue by Gartom** [bitfocus/companion-module-figure53-qlab-advance#52]
Sometimes when loading cues in Qlab the name of the cue does not show up correctly. The name shows correctly within Qlab. It seems to be related to how filenames are stored on network, potentially originally from a Windows PC. All file names show up correctly in both Qlab and Finder on the Mac. If I edit the file name within the Qlab cue list, I can get the Swedish characters to show up correctly in companion

Example:
Button text in companion:
![Button text variable](https://user-images.githubusercontent.com/4034632/115620886-0dac9200-a2f6-11eb-99c8-78c31eddfbb8.png)

File name loaded as cue in Qlab:
![File name](https://user-images.githubusercontent.com/4034632/115620919-18ffbd80-a2f6-11eb-9d81-a381de915d47.png)

Button when cue loaded:
![Button](https://user-images.githubusercontent.com/4034632/115621102-582e0e80-a2f6-11eb-9310-2149eb5b83ba.png)

If I edit the text of the cue within Qlab, I can get it to show åäö ÅÄÖ correctly:
![Button_OK](https://user-images.githubusercontent.com/4034632/115621227-81e73580-a2f6-11eb-8813-115b56ad87fd.png)

**Comment by Gartom** [comment]
Working on a patch myself for this issue but don't have a mac at home so need to wait before I can test it.

**Comment by Gartom** [comment]
I tested my RegExp patch some weeks ago but it didn't work as I hoped. 
I didn't bother to investigate further as I found the workaround to edit the cue names in Qlab instead.

**Comment by istnv** [comment]
That looks like QLab is altering the text when loading the file name. The companion module is displaying the text QLab sends. As you discovered, there is not a simple solution from the companion side.
Closing.
