### ISSUE TITLE
Cannot get feedback from QLAB.

### ISSUE THREAD

**Issue by Raiden38** [bitfocus/companion-module-figure53-qlab-advance#56]
Cannot get any feedback from Q-Lab. In companion, TCP is checked. In Q-Lab, OSC is set. I can send any commands from companion to qlab without any issue. Just cannot get any feedback. In connection, got ERROR instead of OK as soon as I enable TCP. Tried with Local IP, WIFI and Ethernet. Any ideas?

**Comment by istnv** [comment]
What is in the log? Make sure all filters are off to see everything.
Hover over the 'ERROR' box, you should see a pop-up with more details.

**Comment by Raiden38** [comment]
<img width="554" alt="Capture d’écran, le 2022-06-03 à 20 06 40" src="https://user-images.githubusercontent.com/6731214/171968413-13e611ac-03b7-4b89-93d6-c29131f8c9da.png">

**Comment by istnv** [comment]
Looping in @Julusian.
The QLab module has no OSC10 element so this error is coming from another module.
The only module that has OSC10 is the EOS module, which needs to handle this error.

**Comment by Raiden38** [comment]
Just FYI, I do have the ETC-EOS module installed. Connection show as OK. And didn't had any issue with it.. 

Guys, thanks again for your help! :)

**Comment by istnv** [comment]
I do not use the EOS module so it hasn't been an issue. 
There seems to be some variable overlap with some cross-module interaction that should not occur.
It is probably on the QLab side so I'll look into this soon.

**Comment by krocheck** [comment]
No, I think it’s on the EOS side because they modify the osc module that’s imported, which shouldn’t occur globally but definitely seems to be @SteveTherrien

**Comment by Julusian** [comment]
Thanks for the ping. A quick skim looks like etc-eos is patching the osc lib, but they are directly modifying the imported osc object mensing their changes will be leaking into any other usage of osc.
I'll look into it more in the morning

**Comment by Julusian** [comment]
I think I've found the bug in the etc-eos modification of osc that is causing this. It looks like `originalPacketRedirected` was changed to `originalReadPacket` at some point, but one reference was missed.

Please try the latest beta build, I have fixed this typo there. Hopefully that will fix things well enough for now.

I have raised a PR to avoid leaking the modified osc lib, but I need that to be tested before merging, as it is likely to easily break etc-eos if I did something wrong https://github.com/bitfocus/companion-module-etc-eos/pull/15

**Comment by Raiden38** [comment]
Hi @Julusian Thanks so much for the quick fix, so appreaciated!

Unfortunately, I am not sure where to put the new file. I am using the MAC (Intel) version of companion, witch normaly have a install package, so I am not sure where to put the individual files. I looked into the app content, made a search for index.js but could'nt find it. Where can I find more info on instaling that version for mac?

Thanks! :)

**Comment by istnv** [comment]
This was fixed, Closing.
