### ISSUE TITLE
[BUG] Variable $(qlabfb:q_{num}_name) Not Working

### ISSUE THREAD

**Issue by pmc4060** [bitfocus/companion-module-figure53-qlab-advance#57]
I believe this variable should be able to pull the cue name from the inputted cue {num} however i am having difficulty getting that to work.

I'd like to have 10-15 Cues on hot keys on my stream deck showing the correct cue name for each. This will be changing on a daily basis so i'd rather not name the button and then have a cue number trigger button as it may get overlooked.

Please help.

**Comment by pmc4060** [comment]
Help for QLab plugin for Companion with feedback v1.3.10
[2.2.2 (2.2.2+4454-v2-2.2-be663609)](https://bitfocus.io/companion/)

**Comment by istnv** [comment]
How are you typing in the variable? 
The variables are dynamic (not pre-defined) so they do not show in the drop down.

**Comment by pmc4060** [comment]
$(qlabfb:q_{1}_name) \nCue 1 - I belive this should give me something like:

Preset Logo.jpg
Cue 1

as the Icon title? ... At the moment im just getting:
$NA
Cue 1

**Comment by istnv** [comment]
Do not type the braces '{}'. Just `$(qlabfb:q_1_name)`
There should be a couple of examples to help clarify that.

**Comment by pmc4060** [comment]
🤦‍♂️ - I clearly missed those. Had me stumped for over an hour. Thats done the trick Thanks so much!!
