### ISSUE TITLE
QLAB5 Feedback

### ISSUE THREAD

**Issue by JeffreyPeters97** [bitfocus/companion-module-figure53-qlab-advance#68]
Of course is Qlab 5 only been available for a few days but I was trying to connect to companion and it seems that most of the functions work with qlab 5 only the feedback doesn't (TCP). Am I doing something wrong or has the osc changed?

**Comment by istnv** [comment]
You will need a recent beta/developer build for QLab 5. The module dropped back to QLab 3 support if the version was not 4. QLab 3 feedback was minimal. The newer update checks for 5.

**Comment by Raiden38** [comment]
HI everyone! I am not sure to understand what you are saying istnv, but my guess is that a new version of this plugin for companion should be available at some point?

**Comment by istnv** [comment]
@Raiden38 It has been fixed in the beta releases.
