### ISSUE TITLE
Audition button in QLab5

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion-module-figure53-qlab-advance#69]
The Audition button does not work in QLab 5

**Comment by istnv** [comment]
QLab 5 added several different audition windows & modes so the single-mode window no longer works. This will require some time working with QLab 5 to factor in the new options.

**Comment by sstaub** [comment]
In the moment I use raw OSC messages, don't hurry.

**Comment by oneiropagides** [comment]
Hi @sstaub,  how are you doing this,please?
I am trying to simply have a button that launches "Audition Preview" for the selected cue. There is no option for this in the drop-down menu. Is there some workaround I can use?
Thank you!

**Comment by istnv** [comment]
As noted earlier, QLab5 changed how 'Audition' mode works:
The closest option to QLab 4 'Audition Mode' is the 'Always Audition' setting in QLab 5 (which is a different OSC command)
When I get some time this week, I will update companion to use the appropriate command for 'Always Audition' and add some new commands and feedback for QLab5:
- Audition GO, global and cue specific.
- Cue Auditioning feedback in addition to is Running, Stopped, Loaded, Paused
- Workspace 'Audition' mode feedback will match the 'Always Audition' setting.
