### ISSUE TITLE
QLab 5 edit/show mode feedback

### ISSUE THREAD

**Issue by ZachRosing** [bitfocus/companion-module-figure53-qlab-advance#73]
Qlabfb 1.5.3 doesn't correctly read back show/edit mode for button feedback. It always thinks it's in edit mode.

**Comment by istnv** [comment]
This is one of several differences that need to be updated for QLab5.
When I get a chance to update the module, it is on the list as well as passcode permissions and audition windows.

**Comment by dherlein** [comment]
This was working in 5.14 but has broken again in 5.3 (along with the show mode toggle setting)

**Comment by istnv** [comment]
Fixed in beta / companion v3.1
