### ISSUE TITLE
QLab 5 issues

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion-module-figure53-qlab-advance#79]
There are some more issues with qlab 5
- GO button doesn't respect Audition mode
- None variables feedback works

**Comment by sstaub** [comment]
Latest beta 3.0

**Comment by sstaub** [comment]
Sorry, I think it was 2.4.2.

**Comment by istnv** [comment]
QLab 5 defaults to requiring a passcode for most functions. Add a passcode to the module and a matching one in QLab.

**Comment by sstaub** [comment]
Thank you, passcode solved the variable problem. The GO button issue depends on #69, I think.

**Comment by istnv** [comment]
QLab5 does not have the same 'Audition Window' mode as QLab4. 
Closest feature is 'Always Audition'. This is available in module v2.3.0.
