### ISSUE TITLE
Need a variable for workspace ID & for user OSC commands

### ISSUE THREAD

**Issue by Limitedheadroom** [bitfocus/companion-module-figure53-qlab-advance#82]
It would be great to be able to get the workspace ID in to a variable.  And also to ba able to make user OSC messages, with or without arguments.  There are so many features of Qlab 5 accessible via OSC that aren't included in this module, but that we could access.  The Problem is that we can't assign passcodes to the generic OSC module in companion, so even though we can send the message, Qlab won't respond.  This module is the only way to get a passcode sent with the messages, so to be able to build our own OSC messages would solve that.  

Also any workspace OSC messages need the workspace unique ID as part of them, so if this was available as a variable it would open up a lot more user control.

**Comment by istnv** [comment]
Due to family and work issues I have not been able to add any QLab5 features, yet.
You **can** set the workspace ID on the same screen as the IP address.
As you have discovered, you end up hitting limits with the generic OSC module.
Could you make a list of QLab5 features you would like to have added to the module?

**Comment by Limitedheadroom** [comment]
Thanks,  I hadn't noticed the workspace option on the setup page.  

A lot of the features that would be good to have added aren't even Qlab5 specific.  They could be added to the regular Qlab module as they don't need feedback, it's just that that module doesn't allow for passcode either.  `This is why I suggest adding the ability to write our own OSC messages, with option to send string, integer, or float arguments, much like standard companion OSC module.  

The features that need OSC feedback that would be great to have options for are things like, being able to get output names from Qlab.  I know it's possible to get the names, if these could be stored in a variable, so they could be displayed on a button, you could easily see which output fader you were going to bump the level of, PA L, PA R, Sub, Surround etc etc, rather than just 1, 2, 3, 4, etc.

Toggles for things that don't have a control to toggle, where it is possible to query the state.  Such as loop last slice, or integrated fade on off.

Similar to output fader names mentioned above it would be good to be able to get output patch names for things like network, MIDI and anything with an audio output.  

A variable for unique cue ID.  Then the ability to make new cues.  When you do this Qlab returns the unique cue ID of the new cue, this could be saved in that variable and then used..  For example, for moving cues into a recently created group.  Or for retargeting cues to the new cue.  

Command to save the unique cue ID of the selected cue.  It could go in the same previously mentioned variable, but we could then access that variable in other commands.  

Really most of the commands that Qlab can receive via OSC it would be good to be able to access, there are an awful lot of them, so if we could just write them ourself it would surely simplify your coding.  but to have some more variables, as mentioned above that could be integrated into user messages would help hugely.

Sorry, this was a long response.  There is more I'm sure, but this was what came to the top of my head.

**Comment by istnv** [comment]
I appreciate you taking the time to respond!

> A variable for unique cue ID. Then the ability to make new cues. When you do this Qlab returns the unique cue ID of the new cue, this could be saved in that variable and then used.. For example, for moving cues into a recently created group. Or for retargeting cues to the new cue.
> 
> Command to save the unique cue ID of the selected cue. It could go in the same previously mentioned variable, but we could then access that variable in other commands.

These have been in the module for quite a while.
Unique IDs are awkward, but sometimes necessary.
I often work on a workspace with over 10000 cues, very few have actual Cue Numbers.

Look for these in the Help document:
`n_id` and `r_id` are the playhead(next) and running Cue IDs
There is an action available to 'capture' the current playhead Cue ID that wil autofill the next Goto/Start/Sop/Panic (ID) action added to a button.

The others are more audio related and I'll look into them when I get some free time. Using as few 'custom' commands a possible makes simulating a 'toggle' much easier.

**Comment by istnv** [comment]
Workspace ID variable added

**Comment by istnv** [comment]
Transferred remaining ideas to a new Issue
