### ISSUE TITLE
Running Cue Notes variable

### ISSUE THREAD

**Issue by torrymeister** [bitfocus/companion-module-figure53-qlab-advance#83]
A variable for the Running Cue Notes would be very helpful

**Comment by torrymeister** [comment]
Came to think of this would be infeasible as it is possible to run several cues at once

**Comment by istnv** [comment]
The module tries real hard to find the best cue with times to consider as the 'running' cue. This works quite well most of the time unless there are multiple Group cues running at once.
It would be possible to have a 'notes' variable for that particular cue.

**Comment by torrymeister** [comment]
Ok. Then I'd love for that to be implemented

**Comment by istnv** [comment]
It will have the same restriction as the playhead notes (first 20 characters). There is not a lot of space on a button.
