### ISSUE TITLE
Request - Feedback for Timecode

### ISSUE THREAD

**Issue by adaminchicago** [bitfocus/companion-module-figure53-qlab-advance#85]
I’d love to see a Feedback item for so I can monitor LTC coming into QLab by displaying it on the large display above the knobs on the StreamDeck+.  I have cues that are fired by incoming timecode and a little “confidence monitor” would be really slick!

**Comment by istnv** [comment]
That would be nice, but that information is not provided from QLab itself.

**Comment by adaminchicago** [comment]
Ah interesting.  I had assumed that since I am able to watch the incoming time in the Timecode Status window, it was available.  Thanks!

**Comment by istnv** [comment]
They may make it available at some point. Depends on how many people ask. It could add a lot of network traffic.
