### ISSUE TITLE
Request - Variable for Workspace Status

### ISSUE THREAD

**Issue by dherlein** [bitfocus/companion-module-figure53-qlab-advance#87]
Workspace Status can be retrieved as feedback but a variable would be great to allow for things like changing streamdeck pages depending on whether QLab is in show or edit mode

**Comment by istnv** [comment]
For now, you could probably create a trigger 'On condition is true' to watch the status feedback.

**Comment by dherlein** [comment]
Works like a champ

Thanks!
I was totally unaware that you could use triggers to watch feedback and not just variables. This is a much more elegant solution than what I was planning and we'll call this closed as far as I'm concerned

**Comment by istnv** [comment]
It is still on the list when I can get to updating for Q5.
