### ISSUE TITLE
Request - Feedback to show if any cue is playing globally (not just a specific cue)

### ISSUE THREAD

**Issue by lacoustic** [bitfocus/companion-module-figure53-qlab-advance#89]
Wondering if its possible to add in a feature. that if any cue in the whole list (not a specified cue) that it could have a feedback option to turn the play button green to show that theres a cue playing. and red on the stop to indicate no cue is playing. Yellow for pause etc.

I saw theres an option for feedback from a specific cue. but is there a way to do it as a global for any cue in the session.

**Comment by istnv** [comment]
You can probably check that variable `r_id` is not empty.

**Comment by lacoustic** [comment]
Absolutely Brilliant! Thank you for that one :)

**Comment by istnv** [comment]
I still plan to add a direct feedback for easier configuration.
